In [2]:
import numpy as np
import argparse
import cv2

In [8]:
image = cv2.imread("iron_chic.jpg")

In [9]:
(h, w) = image.shape[:2]

In [10]:
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 1.0,
    (300, 300), (104.0, 177.0, 123.0))

In [11]:
net = cv2.dnn.readNetFromCaffe("deploy.prototxt.txt", "res10_300x300_ssd_iter_140000.caffemodel")
net.setInput(blob)
detections = net.forward()

In [12]:
detections.shape

(1, 1, 200, 7)

In [34]:
detections[0, 0, 0]

array([0.        , 1.        , 0.9999083 , 0.52077246, 0.11946487,
       0.86777306, 0.5585621 ], dtype=float32)

In [35]:
detections[0, 0, 1]

array([0.        , 1.        , 0.9985989 , 0.2705257 , 0.25462836,
       0.52284336, 0.6467794 ], dtype=float32)

In [38]:
detections[0, 0, 2]

array([0.        , 1.        , 0.99735343, 0.01240091, 0.30858952,
       0.2786947 , 0.7022801 ], dtype=float32)

In [32]:
for i in range(0, detections.shape[2]):
    print(detections[0, 0, i, 2])

0.9999083
0.9985989
0.99735343
0.11657078
0.10366034
0.09868278
0.09785776
0.09457688
0.09109004
0.08780261
0.08469454
0.08437598
0.08362955
0.08345245
0.08317124
0.083090626
0.082403846
0.08168063
0.08052482
0.080091335
0.07895026
0.078945756
0.07877176
0.078603834
0.078462675
0.078410484
0.0782924
0.07828499
0.078119546
0.07784557
0.07712159
0.07649195
0.07647357
0.07573453
0.075672105
0.07564123
0.07525861
0.074978694
0.07484776
0.07479397
0.07464144
0.07463818
0.07461765
0.074557245
0.074462235
0.07429848
0.07412434
0.074113384
0.07389881
0.0737212
0.07372046
0.07356073
0.073400296
0.07337374
0.07328038
0.07320564
0.07317279
0.07309104
0.07307415
0.07258308
0.072243504
0.072201476
0.07206114
0.07204295
0.07192717
0.07181538
0.07175541
0.07165351
0.07148184
0.07141721
0.07137472
0.07136755
0.071311474
0.07128763
0.07128207
0.07124493
0.071234144
0.071046
0.07101256
0.07082747
0.07082419
0.07080533
0.07077335
0.07075092
0.07068707
0.07058486
0.070530236
0.07046072
0.07035377
0.070309